# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolguard < Formula
  desc "AI-powered security proxy for MCP servers"
  homepage "https://toolguard.ai"
  version "0.5.18"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toolguard/toolguard/releases/download/v0.5.18/toolguard_Darwin_x86_64.tar.gz"
      sha256 "bae2a3e26d3dae38a5f2b93d05687a201d5e379e2ec6f650ae7e3c3f3fe76fc3"

      define_method(:install) do
        bin.install "toolguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toolguard/toolguard/releases/download/v0.5.18/toolguard_Darwin_arm64.tar.gz"
      sha256 "b09f5f89b530ab62722d056c9364fdbed0d12bb7275a2f60443b6bf050672497"

      define_method(:install) do
        bin.install "toolguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toolguard/toolguard/releases/download/v0.5.18/toolguard_Linux_x86_64.tar.gz"
      sha256 "cb191e6b37a8353822580aaeef1c0ff5b8b40d4004ee42d69d2a25b65731ddf5"
      define_method(:install) do
        bin.install "toolguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toolguard/toolguard/releases/download/v0.5.18/toolguard_Linux_arm64.tar.gz"
      sha256 "ee780421a00c8a45791bff9f7ae27178ca2a043b915bf8ab7ca3092fdc4b63b3"
      define_method(:install) do
        bin.install "toolguard"
      end
    end
  end

  test do
    system "#{bin}/toolguard", "version"
  end
end
